[build]
  command = "npm run build"
  publish = "dist/golden-aroma/browser"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
